import { SHARED_BUILDING_CONSTANTS, SHARED_ELEVATOR_CONSTANTS } from './sharedConstants';

export const elevatorConstants = {
  INITIAL_FLOOR: SHARED_ELEVATOR_CONSTANTS.INITIAL_FLOOR,
  SECONDS_TO_MOVE_ONE_FLOOR: SHARED_ELEVATOR_CONSTANTS.SECONDS_TO_MOVE_ONE_FLOOR,
  SECONDS_TO_STOP_AT_FLOOR: SHARED_ELEVATOR_CONSTANTS.SECONDS_TO_STOP_AT_FLOOR,
  POSITION_UPDATE_INTERVAL_MS: SHARED_ELEVATOR_CONSTANTS.POSITION_UPDATE_INTERVAL_MS,
  
  // ערכים מחושבים
  get BOARDING_TIME_SECONDS() {
    return this.SECONDS_TO_STOP_AT_FLOOR * SHARED_ELEVATOR_CONSTANTS.BOARDING_TIME_FRACTION;
  },
  get WARNING_TIME_SECONDS() {
    return this.SECONDS_TO_STOP_AT_FLOOR * SHARED_ELEVATOR_CONSTANTS.WARNING_TIME_FRACTION;
  }
} as const;

export const buildingConstants = {
  INITIAL_TOTAL_FLOORS: SHARED_BUILDING_CONSTANTS.INITIAL_TOTAL_FLOORS,
  INITIAL_ELEVATORS_COUNT: SHARED_BUILDING_CONSTANTS.INITIAL_ELEVATORS_COUNT,
  MIN_ELEVATORS: SHARED_BUILDING_CONSTANTS.MIN_ELEVATORS,
  MAX_ELEVATORS: SHARED_BUILDING_CONSTANTS.MAX_ELEVATORS,
  MIN_FLOORS: SHARED_BUILDING_CONSTANTS.MIN_FLOORS,
  MAX_FLOORS: SHARED_BUILDING_CONSTANTS.MAX_FLOORS,
} as const;