import { SHARED_BUILDING_CONSTANTS, SHARED_NEIGHBORHOOD_CONSTANTS } from './sharedConstants';

export const elevatorConstants = {
  ELEVATOR_WIDTH: 50,
  ELEVATOR_HEIGHT: 40,
  MIN_ELEVATORS: SHARED_BUILDING_CONSTANTS.MIN_ELEVATORS,
  MAX_ELEVATORS: SHARED_BUILDING_CONSTANTS.MAX_ELEVATORS,
} as const;

export const buildingConstants = {
  MIN_FLOORS: SHARED_BUILDING_CONSTANTS.MIN_FLOORS,
  MAX_FLOORS: SHARED_BUILDING_CONSTANTS.MAX_FLOORS,
  FLOOR_PX_HEIGHT: 110,
  DEFAULT_FLOORS_COUNT: SHARED_BUILDING_CONSTANTS.INITIAL_TOTAL_FLOORS,
  MIN_ELEVATORS: SHARED_BUILDING_CONSTANTS.MIN_ELEVATORS,
  ESTIMATE_TIME_UPDATE_THRESHOLD: SHARED_BUILDING_CONSTANTS.ESTIMATE_TIME_UPDATE_THRESHOLD,
  WARNING_FLASH_DURATION: 0.2, // משך הבהוב באדום (בשניות)
} as const;

export const neighborhoodConstants = {
    MIN_BUILDINGS: SHARED_NEIGHBORHOOD_CONSTANTS.MIN_BUILDINGS,
    MAX_BUILDINGS: SHARED_NEIGHBORHOOD_CONSTANTS.MAX_BUILDINGS,
} as const;